### ISSUE TITLE
CronJob definition still uses deprecated/removed API "batch/v1beta1"

### ISSUE THREAD

**Issue by sbalkan-dev** [dodevops/scalyr-k8snode-manager#1]
The API "batch/v1beta1" got removed in kubernetes v1.25 and needs to be migrated to "batch/v1".

See: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125

Attempt to install the chart scalyr-k8snode-manager in version 0.1.6 failed with the following error:

> Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "CronJob" in version "batch/v1beta1"

Tested in environment: Azure AKS v1.25.5

**Comment by dploeger** [comment]
Fixed in 0.1.7 of the chart version. Thanks for reporting!
